version: '3'
services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  phx:
    build: .
    volumes:
      - '.:/app'
    ports:
      - '4008:4008'
    depends_on:
      - postgres
    # command: 'sh -c "trap : TERM INT; tail -f /dev/null & wait"'
    command:
      - ./docker-run.sh
    stdin_open: true
    tty: true
    env_file:
      - .env
